# node_js:
#   - "8"
branches:
  only:
      - /.*/
env:
    - NODEJS_VERSION=8
    - NODEJS_VERSION=9
    - NODEJS_VERSION=10
os:
  - linux
  # - osx
git:
    depth: 5
matrix:
    fast_finish: true
    include:
        # - language: python
        #   python: 3.6
        #   dist: xenial
        #   before_cache:
        #   cache:
        #   before_install:
        #   script: |
        #     bash .ci/code_security_audit.sh

        - os: linux
          dist: xenial
          sudo: required

        - os: linux
          dist: xenial
          sudo: required
          script: |
            bash .ci/ci_check_gm.sh

        - os: osx
          osx_image: xcode11.4

addons:
  apt:
    packages:
    - libssl-dev
    - openssl
  homebrew:
    packages:
    - openssl
before_install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.3/install.sh | bash
  # - source ~/.$(basename $SHELL)rc
install: 
  - nvm install $NODEJS_VERSION 
  - nvm use $NODEJS_VERSION
  - npm install
  - npm run bootstrap
script: |
  bash .ci/ci_check.sh

after_success:
after_failure: